from django.forms import ModelForm
from .models import Feeding

#setting up our autogenerated form for feeding

#extending/inheritin ModelForm to have all it Django Functionalities 
class FeedingForm(ModelForm):
    class Meta:
        #form knows what model it will be working with
        model = Feeding
        #and what fields of model to show
        fields = ["date", "meal"]